language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
script:
  - npm install
  - npm run deploy:gh-pages
  - npm run test:coverage && codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  keep_history: true
  on:
    branch: master
