language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
script:
  - npm run deploy:gh-pages
  - jest -c ./config/test/jest.coverage.json --verbose && codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  keep_history: true
  on:
    branch: codecov-config